I"sb<h2 id="461-what-are-exceptions">46.1. What are Exceptions?</h2>

<p>Things don’t always go according to plan when we’re programming, and when issues arise, we run into exceptions. In this lesson, we’ll learn about what exceptions are and when we’ll run into them.</p>

<h3 id="documentation">Documentation</h3>
<ul>
  <li><a href="https://docs.python.org/3.7/tutorial/errors.html">Python Errors and Exceptions Documentation</a>
 -<a href="https://docs.python.org/3/library/exceptions.html">Python Exceptions Documentation</a></li>
</ul>

<h3 id="syntax-errors-vs-exceptions">Syntax Errors vs Exceptions</h3>

<p>As we’ve been learning how to do various things with Python, we’ve run into both syntax errors and exceptions. There’s a subtle difference between the two: syntax errors cannot be recovered from. The reason that we can’t recover from a syntax error is that our code is simply not valid Python code, so the parser doesn’t know what to do with anything after it runs into the error.</p>

<p>Exceptions are issues that occur during the execution of syntactically valid code that prevents the code from executing as planned. An exception occurring doesn’t necessarily mean that our program needs to fail; it might just mean that we need to do something differently.</p>

<p>An example of an exception that we can handle is a <code class="language-plaintext highlighter-rouge">TypeError</code>. This type of exception that we would run into if we tried to add an <code class="language-plaintext highlighter-rouge">int</code> and a <code class="language-plaintext highlighter-rouge">str</code> like this:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>&gt;&gt;&gt; 1 + 'a'
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
TypeError: unsupported operand type(s) for +: 'int' and 'str'
</code></pre></div></div>

<p>This might seem like something that we would never do, but say we had code that tried to add two different variables, without using type checking or type casting we can’t know for certain that two random variables both hold onto types that can be added, so it is possible to run into a <code class="language-plaintext highlighter-rouge">TypeError</code> in that situation.</p>

<p>As we write more and more complex code, there will be times when we need to handle errors, raise errors ourselves, and even create custom error types.</p>

<h2 id="462-handling-exceptions-with-try-except-else-and-finally">46.2. Handling Exceptions with <code class="language-plaintext highlighter-rouge">try</code>, <code class="language-plaintext highlighter-rouge">except</code>, <code class="language-plaintext highlighter-rouge">else</code>, and <code class="language-plaintext highlighter-rouge">finally</code></h2>

<p>Not everything can go according to plan in our programs, but we should know when these scenarios arise and handle them appropriately. In this lesson, we’ll take a look at how to handle exceptions in Python.</p>

<h3 id="documentation-1">Documentation</h3>

<ul>
  <li><a href="https://docs.python.org/3/reference/compound_stmts.html#the-try-statement">The try statement &amp; workflow</a></li>
  <li><a href="https://docs.python.org/3/reference/compound_stmts.html#the-try-statement">Python Errors and Exceptions Documentation</a></li>
  <li><a href="https://docs.python.org/3/library/exceptions.html">Python Exceptions Documentation</a></li>
</ul>

<h3 id="handling-exceptions-with-tryexceptelsefinally">Handling Exceptions with try/except/else/finally</h3>

<p>When we know that our code can raise an exception, we don’t need to just accept it and let our program crash. We can handle these exceptions using the <a href="https://docs.python.org/3/reference/compound_stmts.html#the-try-statement">try statement</a>. This is a compound statement kind of like the <code class="language-plaintext highlighter-rouge">if</code> statement where we will also need to use <code class="language-plaintext highlighter-rouge">except</code>, and have access to <code class="language-plaintext highlighter-rouge">else</code> and <code class="language-plaintext highlighter-rouge">finally</code>. Let’s break down what these do by writing a small program that will potentially raise an exception. We’ll call this program <code class="language-plaintext highlighter-rouge">using_try.py</code> and put it in a new directory called <code class="language-plaintext highlighter-rouge">exception_handling</code>:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>$ ~/exception_handling
$ touch ~/exception_handling/using_try.py
</code></pre></div></div>

<p><code class="language-plaintext highlighter-rouge">~/exception_handling/using_try.py</code></p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>import sys

print(f"Received argument {sys.argv[1]}")
</code></pre></div></div>
<p>If we run this script with an extra argument, then it will run successfully, but if we run it without any arguments, then we’ll see an exception.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>$ python3.7 using_try.py testing
Received argument testing
$ python3.7 using_try.py
Traceback (most recent call last):
  File "using_try.py", line 3, in &lt;module&gt;
    print(f"Received argument {sys.argv[1]}")
IndexError: list index out of range
</code></pre></div></div>

<p>The exception is an <code class="language-plaintext highlighter-rouge">IndexError</code>, and it’s being raised because the list returned from <code class="language-plaintext highlighter-rouge">sys.argv</code> doesn’t have 2 elements, so there is no index of <code class="language-plaintext highlighter-rouge">1</code>. This is a completely reasonable thing for someone to do when using our script; it is easy to forget to pass in an argument. There are ways to handle this that don’t involve using exception handling, but since indexing a list can potentially raise an exception, we should be ready to perform exception handling in our code.</p>

<p>To handle this, we need to place our code that could raise an exception within a try statement and then <code class="language-plaintext highlighter-rouge">except</code>, if it happens and do something else.</p>

<p><code class="language-plaintext highlighter-rouge">~/exception_handling/using_try.py</code></p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>import sys

try:
    print(f"Received argument {sys.argv[1]}")
except:
    print(f"Error: no arguments, please provide at least one argument")
    sys.exit(1)
</code></pre></div></div>

<p>This is the simplest kind of try/except, and this will catch any exception that might be raised by the code inside the <code class="language-plaintext highlighter-rouge">try</code> block. If we run this file again, we should see our print out.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>$ python3.7 using_try.py
Error: no arguments, please provide at least one argument
$ echo $?
1
</code></pre></div></div>

<p>Since this is still a case where we want to terminate our script, we’re going to explicitly exit with a non-zero status code to indicate the user that things didn’t go according to plan, but we’re also able to shield the user from seeing the Python traceback and provide a better experience to anyone using our script.</p>

<p>We could make this more specific and only <code class="language-plaintext highlighter-rouge">except</code> a very specific exception, and even have multiple separate <code class="language-plaintext highlighter-rouge">except</code> blocks catching different kinds of exceptions. Let’s introduce another potential exception and catch the exceptions separately:</p>

<p><code class="language-plaintext highlighter-rouge">~/exception_handling/using_try.py</code></p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>import sys

try:
    print(f"First argument {sys.argv[1]}")
    args = sys.argv
    random.shuffle(args)
    print(f"Random argument {args[0]}")
except IndexError as err:
    print(f"Error: no arguments, please provide at least one argument ({err})")
    sys.exit(1)
except NameError:
    print(f"Error: random module not loaded")
    sys.exit(1)
</code></pre></div></div>

<p>Let’s run this without an argument and then with an argument:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>$ python3.7 using_try.py
Error: no arguments, please provide at least one argument (list index out of range)
$ python3.7 using_try.py testing
First argument testing
Error: random module not loaded
</code></pre></div></div>

<p>Notice that like a conditional statement with multiple branches, only one of the except blocks will run because as soon as an exception occurs, the execution of the try block stops. Additionally, we can assign the exception that is raised to a variable so that we can get more information from it by adding as <identifier> to our `except` clause.</identifier></p>

<h3 id="the-else-and-finally-statements">The else and finally Statements</h3>

<p>Now we’re able to handle exceptions, but the exception handling workflow also facilitates a way for us to run code if no exception gets caught using <code class="language-plaintext highlighter-rouge">else</code>, and there’s also a way to run some code after any error handling, or the <code class="language-plaintext highlighter-rouge">else</code> block, by using <code class="language-plaintext highlighter-rouge">finally</code>. Since we’re using <code class="language-plaintext highlighter-rouge">sys.exit</code>, we wouldn’t be able to use <code class="language-plaintext highlighter-rouge">finally</code> as is, but let’s make some modifications to see how both of these work.</p>

<p><code class="language-plaintext highlighter-rouge">~/exception_handling/using_try.py</code></p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>import sys
import random

try:
    print(f"First argument {sys.argv[1]}")
    args = sys.argv
    random.shuffle(args)
    print(f"Random argument {args[0]}")
except (IndexError, KeyError) as err:
    print(f"Error: no arguments, please provide at least one argument ({err})")
except NameError:
    print(f"Error: random module not loaded")
else:
    print("Else is running")
finally:
    print("Finally is running")
</code></pre></div></div>

<p>We did import <code class="language-plaintext highlighter-rouge">random</code> so that it is possible to successfully run the script. Let’s give this a run to see how it goes:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>$ python3.7 using_try.py
Error: no arguments, please provide at least one argument (list index out of range)
Finally is running
$ python3.7 using_try.py testing
First argument testing
Random argument using_try.py
Else is running
Finally is running
$
</code></pre></div></div>

<h2 id="463-using-built-in-exceptions">46.3. Using Built-In Exceptions</h2>

<p>When it comes to exceptions most of the time we’ll be using exception handling, but sometimes we want to raise an exception from our code and then expect the code using our code to handle the exceptions that we might potentially raise.</p>

<h3 id="documentation-2">Documentation</h3>
<ul>
  <li><a href="https://docs.python.org/3.7/tutorial/errors.html">Python Errors and Exceptions Documentation</a></li>
  <li><a href="https://docs.python.org/3/library/exceptions.html">Python Exceptions Documentation</a></li>
</ul>

<h3 id="creating-an-exception">Creating an Exception</h3>

<p>To trigger an exception in Python code we need to utilize another keyword: <code class="language-plaintext highlighter-rouge">raise</code>. We refer to this as “raising an exception”. Before we can raise an exception though, we need to create an exception, but thankfully exceptions are objects just like everything else. Hoping into the REPL, let’s create our first exception:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>$ python3.7
&gt;&gt;&gt; err = Exception('something went wrong')
&gt;&gt;&gt; err
Exception('something went wrong')
&gt;&gt;&gt; str(err)
'something went wrong'
&gt;&gt;&gt; dir(err)
['__cause__', '__class__', '__context__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get
attribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__redu
ce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__suppress_context__', '__traceb
ack__', 'args', 'with_traceback']
</code></pre></div></div>

<p>Notice that just creating an exception doesn’t stop excecution. The <code class="language-plaintext highlighter-rouge">Exception</code> class is the parent class for most exceptions, and we can see these by using <code class="language-plaintext highlighter-rouge">Exception.__subclasses__()</code>:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>&gt;&gt;&gt; Exception.__subclasses__()
[&lt;class 'TypeError'&gt;, &lt;class 'StopAsyncIteration'&gt;, &lt;class 'StopIteration'&gt;, &lt;class 'ImportError'&gt;, &lt;class 'OSError'&gt;, &lt;class 'EOFError'&gt;, &lt;class 'RuntimeError'&gt;, &lt;class 'NameError'&gt;, &lt;class 'AttributeError'&gt;, &lt;class 'SyntaxError'&gt;, &lt;class 'LookupError'&gt;, &lt;class 'ValueError'&gt;, &lt;class 'AssertionError'&gt;, &lt;class 'ArithmeticError'&gt;, &lt;class 'SystemError'&gt;, &lt;class 'ReferenceError'&gt;, &lt;class 'MemoryError'&gt;, &lt;class 'BufferError'&gt;, &lt;class 'Warning'&gt;, &lt;class 'locale.Error'&gt;, &lt;class 're.error'&gt;, &lt;class 'sre_parse.Verbose'&gt;]
</code></pre></div></div>

<p>Let’s dig a little deeper into the inheritance struction here:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>&gt;&gt;&gt; Exception.__bases__
(&lt;class 'BaseException'&gt;,)
&gt;&gt;&gt; BaseException.__bases__
(&lt;class 'object'&gt;,)
&gt;&gt;&gt; BaseException.__subclasses__()
[&lt;class 'Exception'&gt;, &lt;class 'GeneratorExit'&gt;, &lt;class 'SystemExit'&gt;, &lt;class 'KeyboardInterrupt'&gt;]
</code></pre></div></div>

<p>Since <code class="language-plaintext highlighter-rouge">BaseException</code> only inherits from <code class="language-plaintext highlighter-rouge">object</code> it is essentially the parent of all errors, but we really won’t ever use it.</p>

<h3 id="raising-an-exception">Raising an Exception</h3>

<p>Now that we know how to create an exception, let’s go ahead and create and raise an exception from a new script called <code class="language-plaintext highlighter-rouge">using_exceptions.py</code>:</p>

<p><code class="language-plaintext highlighter-rouge">~/exception_handling/using_exceptions.py</code></p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>import sys

if len(sys.argv) &lt; 2:
    raise Exception('not enough arguments')

name = sys.argv[1]
print(f"Name is {name}")
</code></pre></div></div>

<p>Now, if we run into the situation where not enough arguments are provided when the script is run we can create and raise an exception with the message that we want. This puts us back to having a not great user experience for our script, but it’s great for showcasing how to use exceptions.</p>

<p>Let’s put this to the test:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>$ python3.7 using_exceptions.py
Traceback (most recent call last):
  File "using_exceptions.py", line 4, in &lt;module&gt;
    raise Exception("not enough arguments")
Exception: not enough arguments
$ python3.7 using_exceptions.py Keith
Name is Keith
</code></pre></div></div>

<h2 id="464-creating-custom-exception-types">46.4. Creating Custom Exception Types</h2>

<p>Specific error types make it easier to tailor exception handling to handle different potential error cases, and sometimes we want to build something that could benefit from having a more detailed error type that doesn’t exist.</p>

<p>In this lesson, we’ll learn how to create custom exception types.</p>

<h3 id="documentation-3">Documentation</h3>

<ul>
  <li><a href="https://docs.python.org/3.7/tutorial/errors.html">Python Errors and Exceptions Tutorial</a></li>
  <li><a href="https://docs.python.org/3/library/exceptions.html">Python Exceptions Documentation</a></li>
</ul>

<h3 id="creating-a-custom-exception-type">Creating a Custom Exception Type</h3>

<p>Custom exception types are things that we’ll use more often when we’re building larger libraries that have different types of contextual errors. These custom exceptions can be caught by the code using our modules so that they only catch our exception and not more generic exceptions. We won’t be creating a large library to showcase custom exceptions, but we can create a simple package that has an <code class="language-plaintext highlighter-rouge">errors</code> module, and then we can raise those errors in the code provided by our package. To begin, let’s create a package called <code class="language-plaintext highlighter-rouge">cli</code>:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>$ mkdir cli
$ touch cli/__init__.py
$ touch cli/errors.py
</code></pre></div></div>

<p>To follow what we’ve been doing around exceptions related to script arguments, let’s create an <code class="language-plaintext highlighter-rouge">ArgumentError</code> class in our <code class="language-plaintext highlighter-rouge">errors</code> module:</p>

<p><code class="language-plaintext highlighter-rouge">~/exception_handling/cli/errors.py</code></p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>class ArgumentError(Exception):
    pass
</code></pre></div></div>

<p>That’s it! Now we have an identifier for our custom exception scenario, but exceptions all need to do the same things, and the <code class="language-plaintext highlighter-rouge">Exception</code> class defines all of that. Let’s create a <code class="language-plaintext highlighter-rouge">main</code> function in our package’s <code class="language-plaintext highlighter-rouge">__init__.py</code> file, and we can run that function from a new script.</p>

<p><code class="language-plaintext highlighter-rouge">~/exception_handling/cli/__init__.py</code></p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>import sys

from .errors import ArgumentError

def main():
    if len(sys.argv) &lt; 2:
        raise ArgumentError('too few arguments')
    print(f"Name is {sys.argv[1]}")
</code></pre></div></div>

<p>From <code class="language-plaintext highlighter-rouge">using_exceptions.py</code>, let’s import our <code class="language-plaintext highlighter-rouge">main</code> function and use exception handling to catch our new <code class="language-plaintext highlighter-rouge">ArgumentError</code>:</p>

<p><code class="language-plaintext highlighter-rouge">~/exception_handling/using_exceptions.py</code></p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>import sys

from cli import main
from cli.errors import ArgumentError

try:
    main()
except ArgumentError as err:
    print(f"Error: {err}")
    sys.exit(1)
</code></pre></div></div>

<p>Finally, let’s run <code class="language-plaintext highlighter-rouge">using_exceptions.py</code> a few more times:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>$ python3.7 using_exceptions.py
Error: too few arguments
$ python3.7 using_exceptions.py Keith
Name is Keith
</code></pre></div></div>

<h2 id="465-using-assertions">46.5. Using Assertions</h2>

<p>When we’ve raised exceptions to this point, we’ve done so because some criteria wasn’t met. When developing and debugging code, this is something that can be done using the built-in <code class="language-plaintext highlighter-rouge">assert</code> keyword, and in this lesson, we’ll give that a try.</p>

<h3 id="documentation-4">Documentation</h3>
<ul>
  <li><a href="https://docs.python.org/3.7/tutorial/errors.html">Python Errors and Exceptions Tutorial</a></li>
  <li><a href="https://docs.python.org/3/library/exceptions.html">Python Exceptions Documentation</a></li>
  <li><a href="https://docs.python.org/3/reference/simple_stmts.html#assert">The assert statement</a></li>
  <li><a href="https://docs.python.org/3/using/cmdline.html#cmdoption-o">The -O Python Flag</a></li>
</ul>

<h3 id="what-is-an-assertion">What is an Assertion?</h3>

<p>Assertions are statements that raise an <code class="language-plaintext highlighter-rouge">AssertionError</code> if the passed in expression returns a <code class="language-plaintext highlighter-rouge">False</code> value (or something that would convert to <code class="language-plaintext highlighter-rouge">False</code> via the <code class="language-plaintext highlighter-rouge">bool</code> constructor). This is what we’ve been doing when we use code like this:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>if len(sys.argv) &lt; 2:
    raise ArgumentError('too few arguments')
</code></pre></div></div>

<p>We can achieve this same thing using an <code class="language-plaintext highlighter-rouge">assert</code> statement, except it will raise an <code class="language-plaintext highlighter-rouge">AssertionError</code> instead of our custom <code class="language-plaintext highlighter-rouge">ArgumentError</code>. Here’s what this would look like in our <code class="language-plaintext highlighter-rouge">main</code> function in the <code class="language-plaintext highlighter-rouge">cli/__init__.py</code> file:</p>

<p><code class="language-plaintext highlighter-rouge">~/exception_handling/cli/__init__.py</code></p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>import sys

from .errors import ArgumentError

def main():
    # if len(sys.argv) &lt; 2:
    #     raise ArgumentError("too few arguments")
    assert len(sys.argv) &gt;= 2, "too few arguments"
    print(f"Name is {sys.argv[1]}")
</code></pre></div></div>

<p>We will need to change our <code class="language-plaintext highlighter-rouge">using_exceptions.py</code> file to except the <code class="language-plaintext highlighter-rouge">AssertionError</code> type to not break our program:</p>

<p><code class="language-plaintext highlighter-rouge">~/exception_handling/using_exceptions.py</code></p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>import sys

from cli import main
from cli.errors import ArgumentError

try:
    main()
except (ArgumentError, AssertionError) as err:
    print(f"Error: {err}")
    sys.exit(1)
Let's run our script once again:

$ python3.7 using_exceptions.py
Error: too few arguments
$ python3.7 using_exceptions.py Keith
Name is Keith
</code></pre></div></div>

<h3 id="assertion-is-a-debugging-tool">Assertion is a debugging Tool</h3>

<p>This isn’t a great use of <code class="language-plaintext highlighter-rouge">assert</code> because assertions are a tool specifically designed for developing and debugging code. The Python parser can remove <code class="language-plaintext highlighter-rouge">assert</code> statements when our script is run with the <code class="language-plaintext highlighter-rouge">-O</code> or <code class="language-plaintext highlighter-rouge">-OO</code> flags (capital ‘o’ for “optimize”).</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>$ python3.7 using_exceptions.py
Error: too few arguments
$ python3.7 -O using_exceptions.py
Traceback (most recent call last):
  File "using_exceptions.py", line 4, in &lt;module&gt;
    main()
  File "/home/cloud_user/exception_handling/cli/__init__.py", line 10, in main
    print(f"Name is {sys.argv[1]}")
IndexError: list index out of range
</code></pre></div></div>

<p>When we use the <code class="language-plaintext highlighter-rouge">-O</code> or <code class="language-plaintext highlighter-rouge">-OO</code> flags, we optimize our code to remove assertions (and docstrings with <code class="language-plaintext highlighter-rouge">-OO</code>), so we can’t reliably use asserts to determine if we’re going to raise errors.</p>

<p>[]:</p>

:ET